name: test_chatbot

on:
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      # リポジトリからチェックアウトして以下の処理を実行
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          # 必要なパッケージインストール
          pip install line-bot-sdk
          pip3 install python-dotenv
          pip3 install requests
          pip3 install BeautifulSoup4
      - name: Run script
        env:
          USER_ID: ${{secrets.USER_ID}}
          CHANNEL_ACCESS_TOKEN: ${{secrets.CHANNEL_ACCESS_TOKEN}}
        run: |
          # main.pyの実行
          python main.py
